feat: first commit of activities
vertigis/workflow-activities-quickbase pull request #3
Opened 2024-10-25 16:26 UTC by cdoak-gh

Quickbase is a new implementation partner that provides a SaaS work management platform. Te platform includes a REST API which we used to integrate Quickbase records with VertiGIS Studio via Workflow. There are a number of professional services projects in the pipeline and these implementations will be greatly improved by a stable and maintained activity pack.

2024-10-25 22:23 UTC, kenlyon commented
I notice an npm audit failure when running `npm install`. I think it's an issue with the Workflow SDK, though. I should create an updated version.

2024-11-05 19:20 UTC, kenlyon requested changes

2024-11-05 19:20 UTC, kenlyon commented on README.md
> +The Quickbase activity pack is intended to be used exclusively by VertiGIS Studio Web applications embedded in browser window within Quickbase, and a secure postMessage communication channel is estab
If this activity pack is exclusively for VSW then I would recommend we remove `EXB` from the `@supportedApps` tag in all of the activities.

2024-11-05 19:20 UTC, kenlyon commented on README.md
> +The Quickbase activity pack is intended to be used exclusively by VertiGIS Studio Web applications embedded in browser window within Quickbase, and a secure postMessage communication channel is estab
> embedded in browser window

We're missing a word here. "embedded in a browser window"?

2024-11-05 19:20 UTC, kenlyon commented on src/activities/CreateQuickbaseService.ts
> +    const quickbaseUri = quickbaseUrl.replace(/\/*$/, "");
It's a small detail, but this regular expression will still match when there's no `/` at the end of the url. It'll replace `""` with `""`.

I doubt there's much of a performance hit with what you have, but `/\/+$/` would only match if there was one or more `/` at the end, which I think is the intended behaviour.

2024-11-05 19:20 UTC, kenlyon commented on src/QuickbaseService.ts
> +    this.instanceUrl = url;
Would it be tidier to clean up the trailing `/` from the url here?

2024-11-05 19:20 UTC, kenlyon commented on src/QuickbaseService.ts
> +  _origin: string;
Should this be `private`?

2024-11-05 19:20 UTC, kenlyon commented on src/QuickbaseService.ts
> +  constructor(url, hostname, origin) {
Missing type declarations on the constructor parameters.

2024-11-05 19:20 UTC, kenlyon commented on src/QuickbaseService.ts
> +      return `QB-TEMP-TOKEN ${qbToken.token}`;;
Extra `;` here.

2024-11-05 19:20 UTC, kenlyon commented on src/QuickbaseService.ts
> +      } else if (message.parameters && message.parameters.token) {
You would get an error here if `message` was `undefined`.

2024-11-05 19:20 UTC, kenlyon commented on src/QuickbaseService.ts
> +    if (!this.hostName) {
Should this be validated in the constructor? I can't see any valid use case where you'd create an instance of the service and not call this method.

2024-11-05 19:20 UTC, kenlyon commented on src/QuickbaseService.ts
> +  instanceUrl: string;
Should this be `readonly` to ensure it's not changed after creation?

2024-11-05 19:20 UTC, kenlyon commented on src/QuickbaseService.ts
> +  hostName: string;
Should this be `readonly` to ensure it's not changed after creation?

2024-11-05 19:20 UTC, kenlyon commented on .gitignore
> +node_modules
(This comment is not related to this file, but I couldn't see a way to add a review comment outside of the changed files.)

I notice an npm audit failure when running `npm install`. If you run `npm audit fix` it will fix it.

2024-11-05 20:03 UTC, cdoak-gh commented on README.md
> +The Quickbase activity pack is intended to be used exclusively by VertiGIS Studio Web applications embedded in browser window within Quickbase, and a secure postMessage communication channel is estab
Fixed.

2024-11-05 20:03 UTC, cdoak-gh commented on README.md
> +The Quickbase activity pack is intended to be used exclusively by VertiGIS Studio Web applications embedded in browser window within Quickbase, and a secure postMessage communication channel is estab
Fixed

2024-11-05 20:04 UTC, cdoak-gh commented on src/activities/CreateQuickbaseService.ts
> +    const quickbaseUri = quickbaseUrl.replace(/\/*$/, "");
Fixed

2024-11-05 20:04 UTC, cdoak-gh commented on src/QuickbaseService.ts
> +    this.instanceUrl = url;
Yeah. That makes sense.  I moved the check.

2024-11-05 20:04 UTC, cdoak-gh commented on src/QuickbaseService.ts
> +  _origin: string;
Yes. Fixed.

2024-11-05 20:05 UTC, cdoak-gh commented on src/QuickbaseService.ts
> +      } else if (message.parameters && message.parameters.token) {
Fixed the message check for undefined.

2024-11-05 20:05 UTC, cdoak-gh commented on src/QuickbaseService.ts
> +    if (!this.hostName) {
I agree. Moved it to the constructor.

2024-11-05 20:05 UTC, cdoak-gh commented on src/QuickbaseService.ts
> +  instanceUrl: string;
Good idea. Fixed.

2024-11-05 20:07 UTC, cdoak-gh commented on src/QuickbaseService.ts
> +  hostName: string;
Yup. Fixed.

2024-11-05 20:07 UTC, cdoak-gh commented on .gitignore
> +node_modules
Ran it and updated the package-lock.json

2024-11-07 16:29 UTC, kenlyon commented on src/QuickbaseService.ts
> +    if (!this.hostName) {
I see the owner and url are now checked in the constructor, but the host is still not validated. Is this an oversight?

2024-11-07 16:52 UTC, cdoak-gh commented on src/QuickbaseService.ts
> +    if (!this.hostName) {
Yes. Fixed.

2025-12-03 17:27 UTC, cdoak-gh commented on src/QuickbaseService.ts
> +  constructor(url, hostname, origin) {
fixed

2025-12-03 17:27 UTC, cdoak-gh commented on src/QuickbaseService.ts
> +      return `QB-TEMP-TOKEN ${qbToken.token}`;;
fixed

2025-12-03 17:37 UTC, kenlyon approved these changes

2025-12-03 17:45 UTC, kenlyon approved these changes

2025-12-03 18:28 UTC, merged